#PBS -S /bin/sh
#PBS -M hyangl@umich.edu
#PBS -A grant_lab
#PBS -q first
#PBS -j oe
#PBS -o out.$PBS_JOBNAME.log
#PBS -V
#PBS -l nodes=1:ppn=8,mem=4000mb,walltime=72:00:00

echo Running job name $PBS_JOBNAME with ID $PBS_JOBID on host $PBS_O_HOST
echo Nodes for run:
cat $PBS_NODEFILE
NPROCS=`wc -l < $PBS_NODEFILE`
echo This job has allocated $NPROCS cores
echo Working directory is $PBS_O_WORKDIR
cd $PBS_O_WORKDIR
echo Time is `date`
echo Directory is `pwd`

./run_md_emin.sh $NPROCS
